// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcq9t3IKzCLl99xuFlpRCG8Ufx1amXkM4',
    appId: '1:1081207055018:web:b42aede7d1ac122894a6d3',
    messagingSenderId: '1081207055018',
    projectId: 'datnminh-787e2',
    authDomain: 'datnminh-787e2.firebaseapp.com',
    storageBucket: 'datnminh-787e2.appspot.com',
    measurementId: 'G-KNDMSHWVXR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGZVNYi7sqmRQTESzxwma3OJx2GMWeoRM',
    appId: '1:1081207055018:android:959a90fad0c46a9594a6d3',
    messagingSenderId: '1081207055018',
    projectId: 'datnminh-787e2',
    storageBucket: 'datnminh-787e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDH_PFllJZDIWyN52ec0f0b_dGkim9UKk',
    appId: '1:1081207055018:ios:e2b7289dcf44527094a6d3',
    messagingSenderId: '1081207055018',
    projectId: 'datnminh-787e2',
    storageBucket: 'datnminh-787e2.appspot.com',
    iosBundleId: 'com.example.travelApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDH_PFllJZDIWyN52ec0f0b_dGkim9UKk',
    appId: '1:1081207055018:ios:a16736d34bf316b994a6d3',
    messagingSenderId: '1081207055018',
    projectId: 'datnminh-787e2',
    storageBucket: 'datnminh-787e2.appspot.com',
    iosBundleId: 'com.example.travelApp.RunnerTests',
  );
}
